# Generated by Django 3.1 on 2020-12-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrashiftsorder',
            name='baqimandeextra',
            field=models.IntegerField(default=0),
        ),
    ]
