# Generated by Django 2.2.10 on 2020-11-22 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('label', models.CharField(choices=[('Mo', 'Morning Shift'), ('Mi', 'Middle Shift'), ('Ni', 'Night Shift')], max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerTitle', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=150)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('RU', 'RUSSIAN'), ('AR', 'ARABIC'), ('TR', 'TURKISH'), ('PR', 'PERSIAN'), ('ES', 'SPANISH'), ('ARM', 'ARMENIAN')], max_length=50)),
                ('shiftManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftDate', models.CharField(max_length=100)),
                ('extraCounter', models.IntegerField(default=0)),
                ('cancelCounter', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField(auto_now_add=True, verbose_name='ORDER TIME ')),
                ('ExtraName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Extra')),
                ('ExtraUsers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
