# Generated by Django 2.2.10 on 2020-11-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocustomuser',
            name='status',
            field=models.CharField(choices=[('RDY', 'Ready'), ('RES', 'Reserve')], default='RDY', max_length=10),
        ),
    ]
