# Generated by Django 2.2.10 on 2020-11-25 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffs',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Languages'),
        ),
        migrations.AddField(
            model_name='shufflers',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shufflers',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Shifts'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Languages'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Managers'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Staffs'),
        ),
        migrations.AddField(
            model_name='managers',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floormanagers',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floormanagers',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Languages'),
        ),
        migrations.AddField(
            model_name='floormanagers',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Shifts'),
        ),
        migrations.AddField(
            model_name='extrashiftsorder',
            name='dealer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Extra.Dealers'),
        ),
        migrations.AddField(
            model_name='extrashifts',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Languages'),
        ),
        migrations.AddField(
            model_name='extrashifts',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Shifts'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealers',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Languages'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extra.Shifts'),
        ),
    ]
