# Generated by Django 2.2.10 on 2020-11-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(choices=[('Mo', 'Morning Shift'), ('Mi', 'Middle Shift'), ('Ni', 'Night Shift')], max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
