# Generated by Django 2.2.10 on 2020-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0002_auto_20201122_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocustomuser',
            name='status',
            field=models.CharField(choices=[('RDY', 'Ready'), ('RES', 'Reserve'), ('BLK', 'BLOCK')], default='RDY', max_length=10),
        ),
    ]
