# Generated by Django 3.1 on 2020-11-30 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraShifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ExtraShift_Date', models.DateField()),
                ('ExtraShift_Time', models.CharField(choices=[('now', 'NOW'), ('10', '10am to 6pm'), ('6', '6pm to 2am'), ('2', '2am to 10am')], max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=12)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Language_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=255)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.languages')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.managers')),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shufflers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.shifts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shifts',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.staffs'),
        ),
        migrations.CreateModel(
            name='FloorManagers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.languages')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.shifts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraShiftsOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dealer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.dealers')),
                ('extraShift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.extrashifts')),
            ],
        ),
        migrations.AddField(
            model_name='extrashifts',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.languages'),
        ),
        migrations.AddField(
            model_name='extrashifts',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.shifts'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.languages'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='shift_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shift_name', to='Cassino_managment_system.shifts'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
