# Generated by Django 3.1 on 2020-11-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cassino_managment_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='shift_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.shifts', to_field='shift_name'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shift_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
