# Generated by Django 3.1 on 2020-12-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cassino_managment_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrashiftsorder',
            old_name='dealer_id',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='extrashiftsorder',
            old_name='extrashift_id',
            new_name='shift',
        ),
    ]
