# Generated by Django 3.1 on 2020-11-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cassino_managment_system', '0002_auto_20201130_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='shift_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cassino_managment_system.shifts'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='shift_name',
            field=models.CharField(max_length=255),
        ),
    ]
