# Generated by Django 3.1 on 2020-11-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cassino_managment_system', '0003_auto_20201130_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrashifts',
            old_name='shift_id',
            new_name='shift_name',
        ),
        migrations.RenameField(
            model_name='extrashiftsorder',
            old_name='extraShift_id',
            new_name='extrashift_name',
        ),
        migrations.RenameField(
            model_name='floormanagers',
            old_name='shift_id',
            new_name='shift_name',
        ),
        migrations.RenameField(
            model_name='shufflers',
            old_name='shift_id',
            new_name='shift_name',
        ),
    ]
