# Generated by Django 2.2.10 on 2020-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('manager', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField()),
                ('quantity', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=50)),
                ('lable', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
