# Generated by Django 2.2.10 on 2020-11-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('RU', 'RUSSIAN'), ('AR', 'ARABIC'), ('TR', 'TURKISH'), ('PR', 'PERSIAN'), ('ES', 'SPANISH'), ('ARM', 'ARMENIAN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('RU', 'RUSSIAN'), ('AR', 'ARABIC'), ('TR', 'TURKISH'), ('PR', 'PERSIAN'), ('ES', 'SPANISH'), ('ARM', 'ARMENIAN')], max_length=10),
        ),
    ]
