# Generated by Django 2.2.10 on 2020-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('DE', 'Dealer'), ('SH', 'Shuffler'), ('FM', 'Floor Manager'), ('LS', 'Live Support'), ('MA', 'Manager')], default='DE', max_length=50),
        ),
    ]
