# Generated by Django 2.2.10 on 2020-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftTitle', models.CharField(max_length=120)),
                ('shiftLanguage', models.CharField(max_length=100)),
                ('shiftManagerName', models.CharField(max_length=100)),
                ('shiftusers', models.CharField(max_length=120)),
            ],
        ),
    ]
