# Generated by Django 2.2.10 on 2020-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('1', 'Dealer'), ('2', 'Shuffler'), ('3', 'Floor Manager'), ('4', 'Live Support'), ('5', 'Manager')], default='1', max_length=50),
        ),
    ]
