# Generated by Django 3.1 on 2020-12-17 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cassino', '0002_extrashiftsorder_baqimandeextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrashiftsorder',
            name='baqimandeextra',
        ),
        migrations.AddField(
            model_name='extrashifts',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrashifts',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrashiftsorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
